CREATE TABLE ADDRESS (
    ADDRESS_ID INTEGER NOT NULL,
    STREET_1 VARCHAR(225),
    STREET_2 VARCHAR(225),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    PIN_CODE INTEGER(6),
    PRIMARY KEY (AddressID)
    
);